### ISSUE TITLE
Issue with open notes

### ISSUE THREAD

**Issue by MavropaliasG** [collinss/Cinnamon-Sticky-Notes#9] opened 2016-05-29 07:42 UTC
if I have clicked the icon in the taskbar there is a small menu that gives me the option to add new note or show/hide notes. If this menu is open and I close the lid of my laptop, the latop goes to suspend but does not lock the screen, so when it resumes I go straight to the desktop with no lock screen.

Mint 17.3

**Comment by collinss** [comment] 2017-02-02 02:40
I'm not sure if this is still an issue for you, but my guess is that it is caused by cinnamon itself and the way the menus intercept signals. I'll close this because I don't believe I can fix it here.

**Closed by collinss** 2017-02-02 02:40 UTC
